
services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  mobile:
    build: 
      context: ./mobile
      dockerfile: dockerfile
    ports:
      - "8081:8081" 
    volumes:
      - /app/node_modules
      - ./mobile:/app
    stdin_open: true
    tty: true
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
