name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create test env file
      run: |
        echo "MONGO_URI=mongodb://test:test@localhost:27017/test" > .env.test
        echo "NODE_ENV=test" >> .env.test
        
    - name: Run tests
      run: npm test